fail test

diff --git a/.github/workflows/12_workflow.yaml b/.github/workflows/12_workflow.yaml
--- a/.github/workflows/12_workflow.yaml
+++ b/.github/workflows/12_workflow.yaml
@@ -6,7 +6,7 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: First step
-        run: sleep 30
+        run: exit 1
       - name: Runs on Canceled
         if: ${{ cancelled() }}
         run: echo "Cancelled"
@@ -19,3 +19,9 @@ jobs:
       - name: Runs an any failure
         if: ${{ failure() }}
         run: echo "Failure"
+  run-second-job:
+    runs-on: ubuntu-latest
+    needs: run-first-command
+    if: ${{ failure() }}
+    steps:
+      - run: echo "Job was failed"
